#!/usr/bin/env bash
# Installing Nginx on my server

sudo apt-get update -y
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo -d "Hello World!" | dd status=none of= /var/www/html/index.nginx-debian.html
service nginx restart
