#!/usr/bin/env bash
# Installing Nginx on my server

sudo apt-get update
sudo apt-get install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
