#!/usr/bin/env bash
# Installing Nginx on my server

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' /var/www/html/index.nginx-debian.html
sudo service nginx restart
