#!/usr/bin/env bash
# Installing Nginx on my server

sudo apt-get update -y
sudo apt-get install nginx -y

sudo ufw allow 'Nginx HTTP'

sudo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

#Redirection using sed
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://edugena.com.ng permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
