#!/usr/bin/env bash
# Installing Nginx on my server

sudo apt-get update -y -qq && \
	sudo apt-get install nginx -y

sudo service nginx start

sudo ufw allow 'Nginx HTTP'
sudo ufw status

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
# Redirection
replacement="server_name _;\n\trewrite ^\\/redirect_me https:\\/\\/www.example.com permanent;"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
