#!/usr/bin/env bash
# Installing Nginx on my server
sudo apt-get update -y -qq && \
	sudo apt-get install nginx -y
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo ufw status
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
# Redirection
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://edugena.com.ng permanent;' /etc/nginx/sites-available/default

#404 redirection
sudo touch /var/www/html/page_404.html
echo "Ceci n'est pas une page\n" >> /var/www/html/page_404.html
sed -i '38i\error_page 404 /page_404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
