#!/usr/bin/env bash
# Installing Nginx on my server

sudo apt-get update -y -qq && \
	sudo apt-get install nginx -y

sudo service nginx start

sudo ufw allow 'Nginx HTTP'
sudo ufw status

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
sudo touch /var/www/html/404page.html
echo "Ceci n'est pas une page" > /var/www/html/404page.html
sed -i '/listen 80 default_Server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /ect/ngninx/sites-available/default

sudo sed -i "/listen 80 default_server;/a error_page 404 .404page.html;" /etc/nginx/sites-available/default

sudo service nginx restart
