#!/usr/bin/env bash
#  Bash script that displays To infinity and beyond indefinitely
#+ In between each iteration of the loop, add a sleep 2.

while true
do
	echo "To infinity and beyong"
	sleep 2
done
