#!/usr/bin/env bash
#Bash script that displays Best School 10 times
#But for the 9th iteration, displays Best Schoo;
#The Hi on a new line

c=0
while [ "$c" -lt 10 ]
do
	if [ "$c" -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	((c++))
done
