#!/usr/bin/env bash
#bash script that loops from 1 to 10 and;
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration 
#displays Best School for the other iteration

c=0
while [ "$c" -lt 10 ]
do
	if [ "$c" -eq 3 ]
	then
		echo "bad luck"

	elif [ "$c" -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((c++))
done
