#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 20 and:
#displays 4 and then bad luck from china for the 4th itereation
#displays 9 and luck from Japan for the 9th loop iterationn
#displays 17 and thenbad luck from italy for the 17th loop iteration

c=1
while [ "$c" -le 20 ]
do
	case $c in
		5)
			echo "bad luck from China"
			;;
		10)
			echo "bad luck from Japan"
			;;
		18)
			echo "bad luck from Italy"
			;;
	esac
	echo "$c"
	((c++))
done
